### ISSUE TITLE
client_secret  issue

### ISSUE THREAD

**Issue by shivbuddhaatcapgemini** [fusionfabric/ffdc-sample-csharp#5]
all the steps in the  readme are great  i was not able to figure the  client_secret  , the link provided for more details (https://developer.ffdcdev.fusionfabric.cloud/documentation/oauth2-grants) is broken, 

Please help

**Comment by vit100** [comment]
try https://developer.fusionfabric.cloud/documentation/oauth2-grants

**Comment by mterente** [comment]
Readme updated
